// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNPkbyrAcpz4pWtsXdEWzXWaLrlqjDEcU',
    appId: '1:797461202277:web:31f2f51a2481645cc78d8c',
    messagingSenderId: '797461202277',
    projectId: 'todo-flutter-app-8304d',
    authDomain: 'todo-flutter-app-8304d.firebaseapp.com',
    storageBucket: 'todo-flutter-app-8304d.firebasestorage.app',
    measurementId: 'G-QJJ76GRB13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZL3kg0NyNHzgMGioau1ls0FW6CembgxM',
    appId: '1:797461202277:android:118fe65286c79cadc78d8c',
    messagingSenderId: '797461202277',
    projectId: 'todo-flutter-app-8304d',
    storageBucket: 'todo-flutter-app-8304d.firebasestorage.app',
  );
}
